"""Adding telegram_accounts table

Revision ID: 14927e20b554
Revises: 8e9d40b0d9a7
Create Date: 2024-12-14 15:54:45.944305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14927e20b554'
down_revision = '8e9d40b0d9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_accounts',
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('telegram_user_id', 'user_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('telegram_accounts')
    # ### end Alembic commands ###