"""Add categories table

Revision ID: 5c789f9afe3e
Revises: 7bb3b55cfae7
Create Date: 2024-11-03 13:02:47.723662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c789f9afe3e'
down_revision = '7bb3b55cfae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('category_title', sa.String(length=30), nullable=False),
    sa.Column('category_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_category_title'), ['category_title'], unique=True)

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.UUID(), nullable=False))
        batch_op.drop_index('ix_tours_tour_type')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['category_id'])
        batch_op.drop_column('tour_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_tours_tour_type', ['tour_type'], unique=False)
        batch_op.drop_column('category_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_category_title'))

    op.drop_table('categories')
    # ### end Alembic commands ###
