"""special offer's correction

Revision ID: 73a099812827
Revises: a8ab2a42c0e5
Create Date: 2024-10-09 22:14:54.862109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a099812827'
down_revision = 'a8ab2a42c0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_offers', schema=None) as batch_op:
        batch_op.alter_column('discount_size',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_offers', schema=None) as batch_op:
        batch_op.alter_column('discount_size',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
