"""adding unique constraint in offers_tours table

Revision ID: 7af3caf8587e
Revises: fe55ec194425
Create Date: 2024-11-25 11:49:49.335248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af3caf8587e'
down_revision = 'fe55ec194425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers_tours',
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['special_offers.offer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.tour_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tour_id', 'offer_id'),
    sa.UniqueConstraint('tour_id', 'offer_id', name='uq_tour_id_offer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers_tours')
    # ### end Alembic commands ###
