"""alter tour_price column in tours from money to decimal

Revision ID: 7b6979d05813
Revises: f9eef316b1bb
Create Date: 2024-11-12 19:21:08.792175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b6979d05813'
down_revision = 'f9eef316b1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.alter_column('tour_price',
               existing_type=postgresql.MONEY(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.alter_column('tour_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=postgresql.MONEY(),
               existing_nullable=False)

    # ### end Alembic commands ###
