"""Moving type column from country table to tour table

Revision ID: 7bb3b55cfae7
Revises: 73a099812827
Create Date: 2024-11-03 12:07:08.305747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb3b55cfae7'
down_revision = '73a099812827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index('ix_countries_country_type')
        batch_op.drop_column('country_type')

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_type', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_tours_tour_type'), ['tour_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tours_tour_type'))
        batch_op.drop_column('tour_type')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_index('ix_countries_country_type', ['country_type'], unique=False)

    # ### end Alembic commands ###
