"""altering discount_size column in special_offers table

Revision ID: 7c330acec352
Revises: 7af3caf8587e
Create Date: 2024-11-27 21:43:53.631785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c330acec352'
down_revision = '7af3caf8587e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('special_offers', schema=None) as batch_op:
        batch_op.alter_column('discount_size',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_offers', schema=None) as batch_op:
        batch_op.alter_column('discount_size',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
