"""countries, tours and other tables

Revision ID: a8ab2a42c0e5
Revises: 9cb324c90433
Create Date: 2024-10-09 22:02:21.831941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8ab2a42c0e5'
down_revision = '9cb324c90433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('country_name', sa.String(length=30), nullable=False),
    sa.Column('country_type', sa.String(length=20), nullable=True),
    sa.Column('country_description', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('country_id')
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_country_name'), ['country_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_countries_country_type'), ['country_type'], unique=False)

    op.create_table('tours',
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('tour_title', sa.String(length=40), nullable=False),
    sa.Column('tour_description', sa.String(length=50), nullable=False),
    sa.Column('tour_text', sa.Text(), nullable=False),
    sa.Column('tour_price', postgresql.MONEY(), nullable=False),
    sa.Column('tour_start_date', sa.Date(), nullable=False),
    sa.Column('tour_end_date', sa.Date(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('tour_id'),
    sa.UniqueConstraint('tour_title')
    )
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tours_tour_end_date'), ['tour_end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tours_tour_price'), ['tour_price'], unique=False)
        batch_op.create_index(batch_op.f('ix_tours_tour_start_date'), ['tour_start_date'], unique=False)

    op.create_table('fav_tours',
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.tour_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('tour_id', 'user_id')
    )
    op.create_table('replies',
    sa.Column('reply_id', sa.UUID(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('parent_reply_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['parent_reply_id'], ['replies.reply_id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.tour_id'], ),
    sa.PrimaryKeyConstraint('reply_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('review_value', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.tour_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('special_offers',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('offer_title', sa.String(length=50), nullable=False),
    sa.Column('discount_size', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.tour_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('special_offers')
    op.drop_table('reviews')
    op.drop_table('replies')
    op.drop_table('fav_tours')
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tours_tour_start_date'))
        batch_op.drop_index(batch_op.f('ix_tours_tour_price'))
        batch_op.drop_index(batch_op.f('ix_tours_tour_end_date'))

    op.drop_table('tours')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_country_type'))
        batch_op.drop_index(batch_op.f('ix_countries_country_name'))

    op.drop_table('countries')
    # ### end Alembic commands ###
