"""alter unique constraint in tours table from tour_title to (tour_title, category_id)

Revision ID: c8a8af90765b
Revises: 7b6979d05813
Create Date: 2024-11-17 01:55:10.399613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a8af90765b'
down_revision = '7b6979d05813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_constraint('tours_tour_title_key', type_='unique')
        batch_op.create_unique_constraint('uq_tour_title_category_id', ['tour_title', 'category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tour_title_category_id', type_='unique')
        batch_op.create_unique_constraint('tours_tour_title_key', ['tour_title'])

    # ### end Alembic commands ###
