"""removing cover_image from countries table

Revision ID: f9eef316b1bb
Revises: 5c789f9afe3e
Create Date: 2024-11-11 20:05:08.921628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9eef316b1bb'
down_revision = '5c789f9afe3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
