"""adding offers_tours table

Revision ID: fe55ec194425
Revises: f09b07b746b6
Create Date: 2024-11-25 09:56:00.883240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe55ec194425'
down_revision = 'f09b07b746b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers_tours',
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['special_offers.offer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.tour_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tour_id', 'offer_id')
    )
    with op.batch_alter_table('special_offers', schema=None) as batch_op:
        batch_op.drop_constraint('special_offers_tour_id_fkey', type_='foreignkey')
        batch_op.drop_column('tour_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('special_offers_tour_id_fkey', 'tours', ['tour_id'], ['tour_id'])

    op.drop_table('offers_tours')
    # ### end Alembic commands ###
