name: CI/CD for Flask and React

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build and Test Flask Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install backend dependencies
        working-directory: flask-backend
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      
      - name: Run backend tests
        working-directory: flask-backend
        run: |
          source venv/bin/activate
          pytest

  build-frontend:
    name: Build and Test React Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install frontend dependencies
        working-directory: react-frontend
        run: |
          npm install
      
      - name: Build frontend
        working-directory: react-frontend
        run: |
          npm run build
      
      - name: Run frontend tests
        working-directory: react-frontend
        run: |
          npm test

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy Backend and Frontend
        run: |
          echo "Deployment scripts go here."
