name: CI/CD for Flask and React

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Flask Backend CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r flask-backend/requirements.txt

    - name: Run tests
      run: |
        cd flask-backend
        pytest

  frontend:
    name: React Frontend CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        cd react-frontend
        npm install

    - name: Run tests
      run: |
        cd react-frontend
        npm test -- --watchAll=false

    - name: Build frontend
      run: |
        cd react-frontend
        npm run build
