name: CI/CD for app

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.4' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flask-backend/requirements.txt
          pip install pytest pytest-cov  # pytest будет использоваться для тестирования
          
      - name: Run tests
        run: pytest --ignore=tests/conftest.py tests/

      # Генерация и загрузка отчёта о покрытии кода тестами на Codecov
      - name: Check code coverage
        run: pytest --cov=flask-backend --cov-report=xml --cov-ignore=tests/conftest.py 
        
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: tests/coverage.xml  # Путь к файлу с отчётом о покрытии
          flags: unittests
